template render_header(fixture: Fixture)
#pragma once

// Generated by Zucchini. Do not edit.

#include <Zucchini/LibZucchini.hpp>
#include <Zucchini/Runtime/ZucchiniRuntime.hpp>

#include <nlohmann/json.hpp>

#include <functional>
#include <bitset>
#include <cstddef>
#include <map>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

namespace n@fixture.namespaceName@
{
    int ZucchiniMain(int argc, char** argv);

    using nZucchini::Zucchini;
    using nZucchini::ZucchiniStep;
    using nZucchini::cell_or;
    using nZucchini::doc_string;
    using nZucchini::require_cell;
    using nZucchini::split_cell;
    using nZucchini::to_bool;
    using nZucchini::to_double;
    using nZucchini::to_long;


    enum class @fixture.stepMethodName@
    {
        @for step in fixture.steps@
        @step.enumCase@,
        @end for@
    };

    inline std::string to_string(@fixture.stepMethodName@ method)
    {
        switch (method)
        {
        @for step in fixture.steps@
        case @fixture.stepMethodName@::@step.enumCase@:
            return "@step.methodName@";
        @end for@
        }
        return "<unknown>";
    }

    @if fixture.hasTags@
    enum class @fixture.stepTagName@
    {
        @for tag in fixture.tags@
        @tag.enumCase@,
        @end for@
    };

    using @fixture.stepTagsName@ =
        nZucchini::TagSet<@fixture.stepTagName@, @fixture.tagCount@>;
    @end if@

    namespace detail
    {
        inline @fixture.stepMethodName@ resolve_step_method(const ZucchiniStep& step)
        {
            @for step in fixture.steps@
            if (step.methodName == "@step.methodName@")
            {
                return @fixture.stepMethodName@::@step.enumCase@;
            }
            @end for@
            throw std::runtime_error("no step method named '" + step.methodName + "'");
        }

        @if fixture.hasTags@
        inline @fixture.stepTagsName@ resolve_step_tags(const ZucchiniStep& step)
        {
            std::bitset<@fixture.tagCount@> bits;
            switch (resolve_step_method(step))
            {
            @for step in fixture.steps@
            case @fixture.stepMethodName@::@step.enumCase@:
                @for tag in step.tags@
                bits.set(static_cast<std::size_t>(@fixture.stepTagName@::@tag@));
                @end for@
                break;
            @end for@
            }
            return @fixture.stepTagsName@(std::move(bits));
        }
        @end if@
    }

    @if fixture.exposeStepMethodWrapper@
    inline @fixture.stepMethodName@ step_method(const ZucchiniStep& step)
    {
        return detail::resolve_step_method(step);
    }
    @end if@

    @if fixture.hasTags@
    @if fixture.exposeStepTagsWrapper@
    inline @fixture.stepTagsName@ step_tags(const ZucchiniStep& step)
    {
        return detail::resolve_step_tags(step);
    }
    @end if@
    @end if@

    @for tag in fixture.tags@
    enum class @tag.stepsTypeName@
    {
        @for method in tag.methods@
        @if method.tagged@
        @method.methodCase@,
        @end if@
        @end for@
    };
    @end for@

    using Row = nZucchini::DataTableRow;

    @for enumeration in fixture.enums@

    @if not enumeration.imported@
    enum class @enumeration.cppName@
    {
        @for enumCase in enumeration.cases@
        @enumCase.identifier@,
        @end for@
    };
    @end if@

    inline bool parse_value(const std::string& text, @enumeration.cppName@& value)
    {
        @for enumCase in enumeration.cases@
        @for candidate in enumCase.values@
        if (text == "@candidate@")
        {
            value = @enumCase.cppName@;
            return true;
        }
        @end for@
        @end for@
        return false;
    }

    inline @enumeration.cppName@ parse_@enumeration.symbolName@(const std::string& text)
    {
        @enumeration.cppName@ value{};
        if (!parse_value(text, value))
        {
            throw std::runtime_error("cannot parse '" + text + "' as @enumeration.cppName@");
        }
        return value;
    }

    inline std::string to_string(@enumeration.cppName@ value)
    {
        @for enumCase in enumeration.cases@
        if (value == @enumCase.cppName@)
        {
            return "@enumCase.identifier@";
        }
        @end for@
        return "<unknown>";
    }

    inline void to_json(nlohmann::json& json, const @enumeration.cppName@& value)
    {
        json = to_string(value);
    }

    inline void from_json(const nlohmann::json& json, @enumeration.cppName@& value)
    {
        value = parse_@enumeration.symbolName@(json.get<std::string>());
    }

    inline std::vector<@enumeration.cppName@> parse_list_@enumeration.symbolName@(
        const std::vector<std::string>& texts)
    {
        std::vector<@enumeration.cppName@> values;
        values.reserve(texts.size());
        for (const auto& text : texts)
        {
            values.push_back(parse_@enumeration.symbolName@(text));
        }
        return values;
    }
    @end for@

    @for structure in fixture.structs@

    @if not structure.imported@
    struct @structure.cppName@
    {
        @for field in structure.fields@
        @field.declType@ @field.cppName@;
        @end for@
        @if structure.additionalProperties@
        std::map<@fixture.stringClassName@, @fixture.stringClassName@> @structure.additionalPropertiesName@;
        @end if@
    };
    @end if@

    inline void parse_value(const Row& row, @structure.cppName@& value)
    {
        @for field in structure.fields@
        value.@field.cppName@ = @field.reader@;
        @end for@
        @if structure.additionalProperties@
        for (const auto& cell : row)
        {
            @for field in structure.fields@
            @for header in field.headers@
            if (cell.first == "@header@")
            {
                continue;
            }
            @end for@
            @end for@
            value.@structure.additionalPropertiesName@.emplace(
                @fixture.stringClassName@(cell.first.c_str()),
                @fixture.stringClassName@(cell.second.c_str()));
        }
        @end if@
    }

    inline @structure.cppName@ parse_@structure.symbolName@(const Row& row)
    {
        @structure.cppName@ value{};
        parse_value(row, value);
        return value;
    }

    inline @structure.cppName@ parse_positional_@structure.symbolName@(const nZucchini::PositionalDataTableRow& cells)
    {
        Row row;
        @for field in structure.fields | enumerator=column@
        if (cells.size() > @column@)
        {
            row["@field.header@"] = cells[@column@];
        }
        @end for@
        return parse_@structure.symbolName@(row);
    }

    inline void to_json(nlohmann::json& json, const @structure.cppName@& value)
    {
        json = nlohmann::json::object();
        @for field in structure.fields@
        @if field.isOptional@
        @if field.isString@
        json["@field.name@"] = value.@field.cppName@ ? nlohmann::json(value.@field.cppName@->@fixture.stringCStrMethod@()) : nlohmann::json();
        @else@
        @if field.isStringList@
        if (value.@field.cppName@)
        {
            auto array = nlohmann::json::array();
            for (const auto& element : *value.@field.cppName@)
            {
                array.push_back(element.@fixture.stringCStrMethod@());
            }
            json["@field.name@"] = std::move(array);
        }
        else
        {
            json["@field.name@"] = nlohmann::json();
        }
        @else@
        json["@field.name@"] = value.@field.cppName@ ? nlohmann::json(*value.@field.cppName@) : nlohmann::json();
        @end if@
        @end if@
        @else@
        @if field.isString@
        json["@field.name@"] = value.@field.cppName@.@fixture.stringCStrMethod@();
        @else@
        @if field.isStringList@
        auto array = nlohmann::json::array();
        for (const auto& element : value.@field.cppName@)
        {
            array.push_back(element.@fixture.stringCStrMethod@());
        }
        json["@field.name@"] = std::move(array);
        @else@
        json["@field.name@"] = value.@field.cppName@;
        @end if@
        @end if@
        @end if@
        @end for@
    }

    inline void from_json(const nlohmann::json& json, @structure.cppName@& value)
    {
        @for field in structure.fields@
        @if field.isOptional@
        if (json.contains("@field.name@") && !json.at("@field.name@").is_null())
        {
            @if field.isString@
            value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
            @else@
            @if field.isStringList@
            value.@field.cppName@.emplace();
            for (const auto& element : json.at("@field.name@"))
            {
                value.@field.cppName@->emplace_back(element.get<std::string>().c_str());
            }
            @else@
            value.@field.cppName@ = json.at("@field.name@").get<@field.valueType@>();
            @end if@
            @end if@
        }
        else
        {
            value.@field.cppName@.reset();
        }
        @else@
        @if field.hasDefault@
        if (json.contains("@field.name@") && !json.at("@field.name@").is_null())
        {
            @if field.isString@
            value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
            @else@
            @if field.isStringList@
            value.@field.cppName@.clear();
            for (const auto& element : json.at("@field.name@"))
            {
                value.@field.cppName@.emplace_back(element.get<std::string>().c_str());
            }
            @else@
            json.at("@field.name@").get_to(value.@field.cppName@);
            @end if@
            @end if@
        }
        else
        {
            value.@field.cppName@ = @field.defaultCode@;
        }
        @else@
        @if field.isString@
        value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
        @else@
        @if field.isStringList@
        value.@field.cppName@.clear();
        for (const auto& element : json.at("@field.name@"))
        {
            value.@field.cppName@.emplace_back(element.get<std::string>().c_str());
        }
        @else@
        json.at("@field.name@").get_to(value.@field.cppName@);
        @end if@
        @end if@
        @end if@
        @end if@
        @end for@
    }

    inline std::vector<@structure.cppName@> parse_rows_@structure.symbolName@(const ZucchiniStep& step)
    {
        std::vector<@structure.cppName@> rows;
        const auto table = nZucchini::DataTable::from_step(step);
        for (const auto& row : table.rows)
        {
            rows.push_back(parse_@structure.symbolName@(row));
        }
        return rows;
    }

    inline std::vector<@structure.cppName@> parse_positional_rows_@structure.symbolName@(const ZucchiniStep& step)
    {
        std::vector<@structure.cppName@> rows;
        const auto table = nZucchini::DataTable::from_step(step);
        for (const auto& cells : table.positionalRows)
        {
            rows.push_back(parse_positional_@structure.symbolName@(cells));
        }
        return rows;
    }
    @end for@

    @for step in fixture.steps@
    @if step.hasArgs@
    struct @step.argsTypeName@
    {
        @for argument in step.arguments@
        @argument.valueType@ @argument.name@;
        @end for@
        explicit @step.argsTypeName@(const ZucchiniStep& step)
            : @for argument in step.arguments | sep=", "@@argument.initializer@@end for@
        {
        }
    };
    @end if@
    @end for@

}

namespace nZucchini
{
    @for tag in fixture.tags@
    template <>
    struct StepTagDescriptor<n@fixture.namespaceName@::@fixture.stepMethodName@,
                             n@fixture.namespaceName@::@fixture.stepTagName@::@tag.enumCase@>
    {
        using StepsType = n@fixture.namespaceName@::@tag.stepsTypeName@;

        static StepsType cast(n@fixture.namespaceName@::@fixture.stepMethodName@ method)
        {
            switch (method)
            {
            @for method in tag.methods@
            case n@fixture.namespaceName@::@fixture.stepMethodName@::@method.methodCase@:
                @if method.tagged@
                return StepsType::@method.methodCase@;
                @else@
                throw std::logic_error("step method does not have the requested tag");
                @end if@
            @end for@
            }
            throw std::logic_error("unknown step method value");
        }
    };
    @end for@

    @for step in fixture.steps@
    @if step.hasArgs@
    template <>
    struct StepTypeDescriptor<n@fixture.namespaceName@::@fixture.stepMethodName@,
                              n@fixture.namespaceName@::@fixture.stepMethodName@::@step.enumCase@>
    {
        using ArgsType = n@fixture.namespaceName@::@step.argsTypeName@;
    };
    @end if@
    @end for@
}

namespace n@fixture.namespaceName@
{
    @if fixture.hasTags@
    template <@fixture.stepTagName@ Tag>
    inline auto cast(@fixture.stepMethodName@ method)
        -> typename nZucchini::StepTagDescriptor<@fixture.stepMethodName@, Tag>::StepsType
    {
        return nZucchini::StepTagDescriptor<@fixture.stepMethodName@, Tag>::cast(method);
    }
    @end if@

    @if fixture.hasTags@
    using @fixture.scenarioContextName@ =
        nZucchini::ScenarioContext<@fixture.stepMethodName@, detail::resolve_step_method,
                                   @fixture.stepTagsName@, detail::resolve_step_tags>;
    @else@
    using @fixture.scenarioContextName@ =
        nZucchini::ScenarioContext<@fixture.stepMethodName@, detail::resolve_step_method>;
    @end if@
    using @fixture.stepViewName@ =
        nZucchini::StepView<@fixture.stepMethodName@, detail::resolve_step_method>;
    @if fixture.hasTags@
    using @fixture.stepContextName@ =
        nZucchini::StepContext<@fixture.stepMethodName@, detail::resolve_step_method,
                               @fixture.stepTagsName@, detail::resolve_step_tags>;
    @else@
    using @fixture.stepContextName@ =
        nZucchini::StepContext<@fixture.stepMethodName@, detail::resolve_step_method>;
    @end if@

    @if fixture.hasTags@
    class @fixture.interfaceName@Interface
            : public nZucchini::ScenarioFixture<@fixture.stepMethodName@, detail::resolve_step_method,
                                                @fixture.stepTagsName@, detail::resolve_step_tags>
    @else@
    class @fixture.interfaceName@Interface
            : public nZucchini::ScenarioFixture<@fixture.stepMethodName@, detail::resolve_step_method>
    @end if@
    {
    public:
        virtual ~@fixture.interfaceName@Interface() = default;

        @for step in fixture.steps@
        virtual void @step.methodName@(@step.parameters@) = 0;
        @end for@

        virtual void @fixture.aroundStepName@(const @fixture.stepContextName@& context, const std::function<void()>& step)
        {
            (void)context;
            step();
        }

        // Runs during discovery; add an error diagnostic to reject a scenario that cannot work.
        virtual void @fixture.validateScenarioName@(const @fixture.scenarioContextName@& context,
                                       nZucchini::Diagnostics& errors)
        {
            (void)context;
            (void)errors;
        }
    };

    class @fixture.interfaceName@
        : public virtual @fixture.interfaceName@Interface
    {
    };

    class @fixture.interfaceName@Decorator : public virtual @fixture.interfaceName@Interface
    {
    public:
        explicit @fixture.interfaceName@Decorator(std::unique_ptr<@fixture.interfaceName@Interface> decorated = nullptr)
            : decorated(std::move(decorated))
        {
        }

        void @fixture.aroundStepName@(const @fixture.stepContextName@& context, const std::function<void()>& step) override
        {
            if (decorated)
            {
                decorated->@fixture.aroundStepName@(context, step);
                return;
            }
            @fixture.interfaceName@Interface::@fixture.aroundStepName@(context, step);
        }

        @for step in fixture.steps@
        void @step.methodName@(@step.parameters@) override
        {
            if (!decorated)
            {
                throw std::logic_error(
                    "@fixture.interfaceName@Decorator::@step.methodName@ has no decorated fixture to forward to");
            }
            decorated->@step.methodName@(@for argument in step.arguments | sep=", "@@argument.name@@end for@);
        }

        @end for@
    protected:
        std::unique_ptr<@fixture.interfaceName@Interface> decorated;
    };

    class @fixture.interfaceName@DefaultThrowing : public virtual @fixture.interfaceName@Interface
    {
    public:
        @for step in fixture.steps@
        void @step.methodName@(@step.parameters@) override
        {
            throw std::logic_error("step '@step.methodName@' is not implemented");
        }

        @end for@
    };
}
END
