template render_header(fixture: Fixture)
#pragma once

// Generated by Zucchini. Do not edit.

#include <Zucchini/LibZucchini.hpp>
#include <Zucchini/Runtime/ZucchiniRuntime.hpp>

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

#include <cucumber/messages/pickle.hpp>

#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace n@fixture.namespaceName@
{
    int ZucchiniMain(int argc, char** argv);

    using nZucchini::Zucchini;
    using nZucchini::ZucchiniStep;

    inline const nZucchini::StepDefinitions kStepDefinitions =
        nlohmann::json::parse(@fixture.stepDefinitionsJson@).get<nZucchini::StepDefinitions>();

    enum class StepMethod
    {
        @for step in fixture.steps@
        @step.enumCase@,
        @end for@
    };

    inline std::string to_string(StepMethod method)
    {
        switch (method)
        {
        @for step in fixture.steps@
        case StepMethod::@step.enumCase@:
            return "@step.methodName@";
        @end for@
        }
        return "<unknown>";
    }

    inline StepMethod step_method(const ZucchiniStep& step)
    {
        @for step in fixture.steps@
        if (step.methodName == "@step.methodName@")
        {
            return StepMethod::@step.enumCase@;
        }
        @end for@
        throw std::runtime_error("no step method named '" + step.methodName + "'");
    }

    using Row = std::map<@fixture.stringClassName@, @fixture.stringClassName@>;

    inline const nZucchini::DataTableArgument& data_table(const ZucchiniStep& step)
    {
        const auto* table = std::get_if<nZucchini::DataTableArgument>(&step.argument);
        if (table == nullptr)
        {
            throw std::runtime_error("step '" + step.text + "' has no data table");
        }
        return *table;
    }

    inline const nZucchini::DocStringArgument& doc_string(const ZucchiniStep& step)
    {
        const auto* content = std::get_if<nZucchini::DocStringArgument>(&step.argument);
        if (content == nullptr)
        {
            throw std::runtime_error("step '" + step.text + "' has no DocString");
        }
        return *content;
    }

    inline std::string cell_text(const nlohmann::json& cell)
    {
        return cell.is_string() ? cell.get<std::string>() : cell.dump();
    }

    inline std::vector<Row> dynamic_rows(const ZucchiniStep& step)
    {
        std::vector<Row> rows;
        for (const auto& row : data_table(step).rows)
        {
            Row cells;
            if (row.is_object())
            {
                for (const auto& cell : row.items())
                {
                    cells[@fixture.stringClassName@(cell.key().c_str())] =
                        @fixture.stringClassName@(cell_text(cell.value()).c_str());
                }
            }
            else
            {
                for (std::size_t column = 0; column < row.size(); ++column)
                {
                    cells[@fixture.stringClassName@(std::to_string(column).c_str())] =
                        @fixture.stringClassName@(cell_text(row[column]).c_str());
                }
            }
            rows.push_back(std::move(cells));
        }
        return rows;
    }

    inline std::vector<std::vector<std::string>> positional_rows(const ZucchiniStep& step)
    {
        std::vector<std::vector<std::string>> rows;
        for (const auto& row : data_table(step).rows)
        {
            std::vector<std::string> cells;
            for (const auto& cell : row)
            {
                    cells.push_back(cell_text(cell));
            }
            rows.push_back(std::move(cells));
        }
        return rows;
    }

    inline std::string require_cell(const Row& row, const std::vector<std::string>& headers)
    {
        for (const auto& header : headers)
        {
            const auto cell = row.find(@fixture.stringClassName@(header.c_str()));
            if (cell != row.end())
            {
                return std::string(cell->second.@fixture.stringCStrMethod@());
            }
        }

        std::string message = "data table is missing a required column; expected one of: ";
        for (std::size_t index = 0; index < headers.size(); ++index)
        {
            message += (index == 0 ? "'" : ", '") + headers[index] + "'";
        }
        throw std::runtime_error(message);
    }

    inline std::string cell_or(const Row& row,
                               const std::vector<std::string>& headers,
                               const std::string& fallback)
    {
        for (const auto& header : headers)
        {
            const auto cell = row.find(@fixture.stringClassName@(header.c_str()));
            if (cell != row.end())
            {
                return std::string(cell->second.@fixture.stringCStrMethod@());
            }
        }
        return fallback;
    }

    inline std::vector<std::string> split_cell(const std::string& value, char separator)
    {
        std::vector<std::string> parts;
        std::istringstream stream(value);
        std::string part;
        while (std::getline(stream, part, separator))
        {
            const auto first = part.find_first_not_of(" \t\r\n");
            const auto last = part.find_last_not_of(" \t\r\n");
            part = first == std::string::npos ? std::string() : part.substr(first, last - first + 1);
            parts.push_back(part);
        }
        return parts;
    }

    inline long to_long(const std::string& value)
    {
        return std::stol(value);
    }

    inline double to_double(const std::string& value)
    {
        return std::stod(value);
    }

    inline bool to_bool(const std::string& value)
    {
        return value == "true" || value == "True" || value == "TRUE" ||
               value == "yes" || value == "Yes" || value == "YES" ||
               value == "1";
    }
    @for enumeration in fixture.enums@

    @if not enumeration.imported@
    enum class @enumeration.cppName@
    {
        @for enumCase in enumeration.cases@
        @enumCase.identifier@,
        @end for@
    };
    @end if@

    inline bool parse_value(const std::string& text, @enumeration.cppName@& value)
    {
        @for enumCase in enumeration.cases@
        @for candidate in enumCase.values@
        if (text == "@candidate@")
        {
            value = @enumCase.cppName@;
            return true;
        }
        @end for@
        @end for@
        return false;
    }

    inline @enumeration.cppName@ parse_@enumeration.symbolName@(const std::string& text)
    {
        @enumeration.cppName@ value{};
        if (!parse_value(text, value))
        {
            throw std::runtime_error("cannot parse '" + text + "' as @enumeration.cppName@");
        }
        return value;
    }

    inline std::string to_string(@enumeration.cppName@ value)
    {
        @for enumCase in enumeration.cases@
        if (value == @enumCase.cppName@)
        {
            return "@enumCase.identifier@";
        }
        @end for@
        return "<unknown>";
    }

    inline void to_json(nlohmann::json& json, const @enumeration.cppName@& value)
    {
        json = to_string(value);
    }

    inline void from_json(const nlohmann::json& json, @enumeration.cppName@& value)
    {
        value = parse_@enumeration.symbolName@(json.get<std::string>());
    }

    inline std::vector<@enumeration.cppName@> parse_list_@enumeration.symbolName@(
        const std::vector<std::string>& texts)
    {
        std::vector<@enumeration.cppName@> values;
        values.reserve(texts.size());
        for (const auto& text : texts)
        {
            values.push_back(parse_@enumeration.symbolName@(text));
        }
        return values;
    }
    @end for@
    @for structure in fixture.structs@

    @if not structure.imported@
    struct @structure.cppName@
    {
        @for field in structure.fields@
        @field.declType@ @field.cppName@;
        @end for@
        @if structure.additionalProperties@
        std::map<@fixture.stringClassName@, @fixture.stringClassName@> additionalProperties;
        @end if@
    };
    @end if@

    inline void parse_value(const Row& row, @structure.cppName@& value)
    {
        @for field in structure.fields@
        value.@field.cppName@ = @field.reader@;
        @end for@
        @if structure.additionalProperties@
        for (const auto& cell : row)
        {
            @for field in structure.fields@
            @for header in field.headers@
            if (cell.first == @fixture.stringClassName@(std::string("@header@").c_str()))
            {
                continue;
            }
            @end for@
            @end for@
            value.additionalProperties.insert(cell);
        }
        @end if@
    }

    inline @structure.cppName@ parse_@structure.symbolName@(const Row& row)
    {
        @structure.cppName@ value{};
        parse_value(row, value);
        return value;
    }

    inline @structure.cppName@ parse_positional_@structure.symbolName@(const std::vector<std::string>& cells)
    {
        Row row;
        @for field in structure.fields | enumerator=column@
        if (cells.size() > @column@)
        {
            row[@fixture.stringClassName@(std::string("@field.header@").c_str())] =
                @fixture.stringClassName@(cells[@column@].c_str());
        }
        @end for@
        return parse_@structure.symbolName@(row);
    }

    inline void to_json(nlohmann::json& json, const @structure.cppName@& value)
    {
        json = nlohmann::json::object();
        @for field in structure.fields@
        @if field.isOptional@
        @if field.isString@
        json["@field.name@"] = value.@field.cppName@ ? nlohmann::json(value.@field.cppName@->@fixture.stringCStrMethod@()) : nlohmann::json();
        @else@
        @if field.isStringList@
        if (value.@field.cppName@)
        {
            auto array = nlohmann::json::array();
            for (const auto& element : *value.@field.cppName@)
            {
                array.push_back(element.@fixture.stringCStrMethod@());
            }
            json["@field.name@"] = std::move(array);
        }
        else
        {
            json["@field.name@"] = nlohmann::json();
        }
        @else@
        json["@field.name@"] = value.@field.cppName@ ? nlohmann::json(*value.@field.cppName@) : nlohmann::json();
        @end if@
        @end if@
        @else@
        @if field.isString@
        json["@field.name@"] = value.@field.cppName@.@fixture.stringCStrMethod@();
        @else@
        @if field.isStringList@
        auto array = nlohmann::json::array();
        for (const auto& element : value.@field.cppName@)
        {
            array.push_back(element.@fixture.stringCStrMethod@());
        }
        json["@field.name@"] = std::move(array);
        @else@
        json["@field.name@"] = value.@field.cppName@;
        @end if@
        @end if@
        @end if@
        @end for@
    }

    inline void from_json(const nlohmann::json& json, @structure.cppName@& value)
    {
        @for field in structure.fields@
        @if field.isOptional@
        if (json.contains("@field.name@") && !json.at("@field.name@").is_null())
        {
            @if field.isString@
            value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
            @else@
            @if field.isStringList@
            value.@field.cppName@.emplace();
            for (const auto& element : json.at("@field.name@"))
            {
                value.@field.cppName@->emplace_back(element.get<std::string>().c_str());
            }
            @else@
            value.@field.cppName@ = json.at("@field.name@").get<@field.valueType@>();
            @end if@
            @end if@
        }
        else
        {
            value.@field.cppName@.reset();
        }
        @else@
        @if field.hasDefault@
        if (json.contains("@field.name@") && !json.at("@field.name@").is_null())
        {
            @if field.isString@
            value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
            @else@
            @if field.isStringList@
            value.@field.cppName@.clear();
            for (const auto& element : json.at("@field.name@"))
            {
                value.@field.cppName@.emplace_back(element.get<std::string>().c_str());
            }
            @else@
            json.at("@field.name@").get_to(value.@field.cppName@);
            @end if@
            @end if@
        }
        else
        {
            value.@field.cppName@ = @field.defaultCode@;
        }
        @else@
        @if field.isString@
        value.@field.cppName@ = @field.valueType@(json.at("@field.name@").get<std::string>().c_str());
        @else@
        @if field.isStringList@
        value.@field.cppName@.clear();
        for (const auto& element : json.at("@field.name@"))
        {
            value.@field.cppName@.emplace_back(element.get<std::string>().c_str());
        }
        @else@
        json.at("@field.name@").get_to(value.@field.cppName@);
        @end if@
        @end if@
        @end if@
        @end if@
        @end for@
    }

    inline std::vector<@structure.cppName@> parse_rows_@structure.symbolName@(const ZucchiniStep& step)
    {
        std::vector<@structure.cppName@> rows;
        for (const auto& row : dynamic_rows(step))
        {
            rows.push_back(parse_@structure.symbolName@(row));
        }
        return rows;
    }

    inline std::vector<@structure.cppName@> parse_positional_rows_@structure.symbolName@(const ZucchiniStep& step)
    {
        std::vector<@structure.cppName@> rows;
        for (const auto& cells : positional_rows(step))
        {
            rows.push_back(parse_positional_@structure.symbolName@(cells));
        }
        return rows;
    }
    @end for@

    struct StepView
    {
        StepMethod method;
        const ZucchiniStep& step;
    };

    struct StepContext
    {
        const Zucchini& zucchini;
        std::size_t index = 0;

        StepView current() const
        {
            const auto& step = zucchini.steps.at(index);
            return StepView{step_method(step), step};
        }

        std::optional<StepView> previous() const
        {
            if (index == 0)
            {
                return std::nullopt;
            }
            const auto& step = zucchini.steps.at(index - 1);
            return StepView{step_method(step), step};
        }

        std::optional<StepView> next() const
        {
            if (index + 1 >= zucchini.steps.size())
            {
                return std::nullopt;
            }
            const auto& step = zucchini.steps.at(index + 1);
            return StepView{step_method(step), step};
        }
    };

    class @fixture.interfaceName@Interface
    {
    public:
        virtual ~@fixture.interfaceName@Interface() = default;

        @for step in fixture.steps@
        virtual void @step.methodName@(@step.parameters@) = 0;
        @end for@

        virtual void @fixture.aroundStepName@(const StepContext& context, const std::function<void()>& step)
        {
            (void)context;
            step();
        }

        // Runs during discovery; add an error diagnostic to reject a scenario that cannot work.
        virtual void @fixture.validateScenarioName@(const Zucchini& zucchini,
                                       const cucumber::messages::pickle& pickle,
                                       nZucchini::Diagnostics& errors)
        {
            (void)zucchini;
            (void)pickle;
            (void)errors;
        }
    };

    class @fixture.interfaceName@
        : public virtual @fixture.interfaceName@Interface
        , public testing::TestWithParam<Zucchini>
    {
    };

    class @fixture.interfaceName@Decorator : public virtual @fixture.interfaceName@Interface
    {
    public:
        explicit @fixture.interfaceName@Decorator(std::unique_ptr<@fixture.interfaceName@Interface> decorated = nullptr)
            : decorated(std::move(decorated))
        {
        }

        void @fixture.aroundStepName@(const StepContext& context, const std::function<void()>& step) override
        {
            if (decorated)
            {
                decorated->@fixture.aroundStepName@(context, step);
                return;
            }
            @fixture.interfaceName@Interface::@fixture.aroundStepName@(context, step);
        }

        @for step in fixture.steps@
        void @step.methodName@(@step.parameters@) override
        {
            if (!decorated)
            {
                throw std::logic_error(
                    "@fixture.interfaceName@Decorator::@step.methodName@ has no decorated fixture to forward to");
            }
            decorated->@step.methodName@(@for argument in step.arguments | sep=", "@@argument.name@@end for@);
        }

        @end for@
    protected:
        std::unique_ptr<@fixture.interfaceName@Interface> decorated;
    };

    class @fixture.interfaceName@DefaultThrowing : public virtual @fixture.interfaceName@Interface
    {
    public:
        @for step in fixture.steps@
        void @step.methodName@(@step.parameters@) override
        {
            throw std::logic_error("step '@step.methodName@' is not implemented");
        }

        @end for@
    };
}
END
