template render_test(fixture: Fixture)
// Generated by Zucchini. Do not edit.
// Expects a class @fixture.name@ deriving from n@fixture.namespaceName@::@fixture.interfaceName@ in "@fixture.sourceName@.h".

#include <iostream>
#include <Zucchini/LibZucchini.hpp>
#include <Zucchini/Runtime/ZucchiniRuntime.hpp>
#include "@fixture.sourceName@.h"

namespace n@fixture.namespaceName@
{
    // gtest fixtures are abstract until TEST_P defines TestBody, so discovery uses this shim.
    struct ValidationFixture : @fixture.name@
    {
        void TestBody() override
        {
        }
    };

    void runScenario(const Zucchini& zucchini, @fixture.interfaceName@Interface& fixture);

    void validateArguments(const Zucchini& zucchini, nZucchini::Diagnostics& errors)
    {
        for (std::size_t index = 0; index < zucchini.steps.size(); ++index)
        {
            const auto& step = zucchini.steps[index];
            try
            {
                switch (step_method(step))
                {
                @for step in fixture.steps@
                case StepMethod::@step.enumCase@:
                {
                    @for argument in step.arguments@
                    @argument.declaration@
                    (void)@argument.name@;
                    @end for@
                    break;
                }
                @end for@
                }
            }
            catch (const std::exception& failure)
            {
                nZucchini::add_diagnostic(errors,
                                          zucchini.uri,
                                          failure.what(),
                                          step.line,
                                          step.column);
            }
        }
    }

    TEST_P(@fixture.name@, RunsScenario)
    {
        runScenario(GetParam(), *this);
    }

    INSTANTIATE_TEST_SUITE_P(Zucchinis,
                             @fixture.name@,
                             nZucchini::zucchini_values(),
                             nZucchini::zucchini_test_name);

    void runScenario(const Zucchini& zucchini, @fixture.interfaceName@Interface& fixture)
    {
        std::vector<std::function<void()>> boundSteps;
        boundSteps.reserve(zucchini.steps.size());

        for (const auto& step : zucchini.steps)
        {
            switch (step_method(step))
            {
            @for step in fixture.steps@
            case StepMethod::@step.enumCase@:
            {
                @for argument in step.arguments@
                @argument.declaration@
                @end for@
                boundSteps.emplace_back(
                    [&fixture@for argument in step.arguments@, @argument.name@@end for@] {
                        fixture.@step.methodName@(@for argument in step.arguments | sep=", "@@argument.name@@end for@);
                    });
                break;
            }
            @end for@
            }
        }

        for (std::size_t index = 0; index < boundSteps.size(); ++index)
        {
            const auto& step = zucchini.steps[index];
            nZucchini::set_current_source_location(
                nZucchini::SourceLocation(zucchini.uri, step.line, step.column, step.text));

            const StepContext context{zucchini, index};
            fixture.@fixture.aroundStepName@(context, boundSteps[index]);
        }

        nZucchini::clear_current_source_location();
    }
}

int main(int argc, char** argv)
{
    nZucchini::install_zucchini_provider(
        argc,
        argv,
        n@fixture.namespaceName@::kStepDefinitions,
        [](const nZucchini::Zucchini& zucchini,
           const cucumber::messages::pickle& pickle,
           nZucchini::Diagnostics& errors) {
            n@fixture.namespaceName@::validateArguments(zucchini, errors);
            n@fixture.namespaceName@::ValidationFixture fixture;
            static_cast<n@fixture.namespaceName@::@fixture.interfaceName@Interface&>(fixture).
                @fixture.validateScenarioName@(zucchini, pickle, errors);
        },
        @fixture.snippetMethodCasing@,
        @fixture.snippetClassCasing@);
    return nZucchini::ZucchiniMain(argc, argv);
}
END
