template render_test(fixture: Fixture)
// Generated by Zucchini. Do not edit.

@for include in fixture.commonIncludes@
#include "@include@"
@end for@
#include <gtest/gtest.h>
#include <Zucchini/LibZucchini.hpp>
#include <Zucchini/Runtime/ZucchiniRuntime.hpp>
#include <nlohmann/json.hpp>
#include "@fixture.sourceName@.h"

#include <cstdlib>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

namespace n@fixture.namespaceName@
{
    void validate_step_arguments(const Zucchini& zucchini,
                                 nZucchini::Diagnostics& errors)
    {
        for (const auto& step : zucchini.steps)
        {
            try
            {
                switch (detail::resolve_step_method(step))
                {
                @for step in fixture.steps@
                case @fixture.stepMethodName@::@step.enumCase@:
                {
                    @if step.hasArgs@
                    using ArgsType = typename nZucchini::StepTypeDescriptor<@fixture.stepMethodName@,
                        @fixture.stepMethodName@::@step.enumCase@>::ArgsType;
                    (void)ArgsType(step);
                    @end if@
                    break;
                }
                @end for@
                }
            }
            catch (const std::exception& failure)
            {
                nZucchini::add_diagnostic(errors, zucchini.uri, failure.what(),
                                          step.line, step.column);
            }
        }
    }

    class ScenarioTest : public @fixture.name@, public testing::Test
    {
    public:
        ScenarioTest(std::string planName, std::string manifestDirectory)
            : planName(std::move(planName)),
              manifestDirectory(std::move(manifestDirectory))
        {
        }

        void SetUp() override { @fixture.name@::SetUp(); }
        void TearDown() override { @fixture.name@::TearDown(); }

        void TestBody() override
        {
            Zucchini plan;
            nZucchini::Diagnostics errors;
            if (!nZucchini::load_execution_plan(manifestDirectory, planName,
                                                plan, errors))
            {
                ADD_FAILURE() << nZucchini::to_string(errors);
                return;
            }

            this->execute_plan(
                plan,
                [this](const @fixture.stepContextName@& context,
                       const std::function<void()>& step) {
                    this->@fixture.aroundStepName@(context, step);
                },
                [this](const ZucchiniStep& step) {
                    switch (detail::resolve_step_method(step))
                    {
                    @for step in fixture.steps@
                    case @fixture.stepMethodName@::@step.enumCase@:
                    {
                        @if step.hasArgs@
                        using ArgsType = typename nZucchini::StepTypeDescriptor<@fixture.stepMethodName@,
                            @fixture.stepMethodName@::@step.enumCase@>::ArgsType;
                        const ArgsType args(step);
                        @end if@
                        this->@step.methodName@(@for argument in step.arguments | sep=", "@args.@argument.name@@end for@);
                        break;
                    }
                    @end for@
                    }
                });
        }

    private:
        std::string planName;
        std::string manifestDirectory;
    };

    class SourceLocationListener : public testing::EmptyTestEventListener
    {
    public:
        void OnTestPartResult(const testing::TestPartResult& result) override
        {
            if (!result.failed()) return;
            const auto* location = nZucchini::current_source_location();
            if (location == nullptr) return;
            std::cout << "gherkin source:\n" << nZucchini::to_string(*location);
            if (!location->stepText.empty()) std::cout << ": " << location->stepText;
            std::cout << std::endl;
        }
    };

    void report_diagnostics(const std::string& prefix,
                            const nZucchini::Diagnostics& errors)
    {
        if (!errors.empty()) std::cerr << prefix << nZucchini::to_string(errors) << std::endl;
    }

    int ZucchiniMain(int argc, char** argv)
    {
        testing::InitGoogleTest(&argc, argv);
        testing::UnitTest::GetInstance()->listeners().Append(
            new SourceLocationListener());

        const auto args = nZucchini::parse_discovery_args(argc, argv);
        std::vector<std::string> planNames;
        if (GTEST_FLAG_GET(list_tests) && !args.featureDir.empty())
        {
            const nZucchini::StepDefinitions kStepDefinitions =
                nlohmann::json::parse(@fixture.stepDefinitionsJson@).get<nZucchini::StepDefinitions>();
            const auto discovery = nZucchini::discover_feature_files(
                args.featureDir, kStepDefinitions, @fixture.methodsCasing@,
                @fixture.typesCasing@, @fixture.variablesCasing@);
            report_diagnostics("cannot parse features in '" + args.featureDir + "':",
                               discovery.errors);
            if (nZucchini::has_errors(discovery.errors)) return EXIT_FAILURE;
            if (!discovery.undefinedStepSuggestions.empty())
            {
                std::cerr << "undefined steps in '" << args.featureDir
                          << "'; add these step definitions:\n\n"
                          << discovery.undefinedStepSuggestions << std::endl;
                return EXIT_FAILURE;
            }

            @fixture.name@ fixture;
            nZucchini::Diagnostics planErrors;
            nZucchini::Diagnostics scenarioDiagnostics;
            const auto plans = fixture.make_execution_plans(
                discovery, kStepDefinitions,
                [](const nZucchini::Zucchini& zucchini,
                   nZucchini::Diagnostics& errors) {
                    validate_step_arguments(zucchini, errors);
                },
                [&fixture](const @fixture.scenarioContextName@& context,
                           nZucchini::Diagnostics& errors) {
                    fixture.@fixture.validateScenarioName@(context, errors);
                },
                planErrors, scenarioDiagnostics);
            report_diagnostics("cannot parse features in '" + args.featureDir + "':",
                               planErrors);
            report_diagnostics("scenario diagnostics:", scenarioDiagnostics);
            if (nZucchini::has_errors(planErrors) ||
                nZucchini::has_errors(scenarioDiagnostics)) return EXIT_FAILURE;

            nZucchini::Diagnostics storeErrors;
            if (!nZucchini::store_execution_plans(args.manifestDir, plans,
                                                  storeErrors))
            {
                report_diagnostics("cannot store execution plans:", storeErrors);
                return EXIT_FAILURE;
            }
            for (const auto& plan : plans)
            {
                planNames.push_back(nZucchini::execution_plan_name(plan));
            }
        }
        else
        {
            nZucchini::Diagnostics loadErrors;
            if (!nZucchini::list_execution_plan_names(args.manifestDir,
                                                      planNames, loadErrors))
            {
                report_diagnostics("cannot list execution plans:", loadErrors);
                return EXIT_FAILURE;
            }
        }

        for (const auto& planName : planNames)
        {
            testing::RegisterTest(
                "@fixture.name@", planName.c_str(), nullptr, planName.c_str(),
                __FILE__, __LINE__,
                [planName, manifestDirectory = args.manifestDir]() -> testing::Test* {
                    return new ScenarioTest(planName, manifestDirectory);
                });
        }
        return RUN_ALL_TESTS();
    }
}
END
