template render_test(fixture: Fixture)
// Generated by Zucchini. Do not edit.
// Expects a class @fixture.name@ deriving from n@fixture.name@::I@fixture.name@ in "@fixture.name@.h".

#include "I@fixture.name@.h"
#include "@fixture.name@.h"

#include <Zucchini/Diagnostics.hpp>
#include <Zucchini/Discovery.hpp>
#include <Zucchini/ManifestParser.hpp>
#include <Zucchini/SourceLocation.hpp>
#include <Zucchini/ZucchiniMain.hpp>

#include <functional>
#include <iostream>
#include <vector>

namespace n@fixture.name@
{
    void runScenario(const Zucchini& zucchini, @fixture.name@Interface& fixture);

    TEST_P(@fixture.name@, RunsScenario)
    {
        runScenario(GetParam(), *this);
    }

    INSTANTIATE_TEST_SUITE_P(Zucchinis,
                             @fixture.name@,
                             nZucchini::zucchini_values(),
                             nZucchini::zucchini_test_name);

    void runScenario(const Zucchini& zucchini, @fixture.name@Interface& fixture)
    {
        std::vector<std::function<void()>> boundSteps;
        boundSteps.reserve(zucchini.steps.size());

        for (const auto& step : zucchini.steps)
        {
            switch (step_method(step))
            {
            @for step in fixture.steps@
            case StepMethod::@step.enumCase@:
            {
                @for argument in step.arguments@
                @argument.declaration@
                @end for@
                boundSteps.emplace_back(
                    [&fixture@for argument in step.arguments@, @argument.name@@end for@] {
                        fixture.@step.methodName@(@for argument in step.arguments | sep=", "@@argument.name@@end for@);
                    });
                break;
            }
            @end for@
            }
        }

        for (std::size_t index = 0; index < boundSteps.size(); ++index)
        {
            const auto& step = zucchini.steps[index];
            nZucchini::set_current_source_location(
                nZucchini::SourceLocation(zucchini.uri, step.line, step.column, step.text));

            const StepContext context{zucchini, index};
            fixture.aroundStep(context, boundSteps[index]);
        }

        nZucchini::clear_current_source_location();
    }
}

int main(int argc, char** argv)
{
    nZucchini::StepDefManifest manifest;
    nZucchini::Diagnostics errors;
    if (!nZucchini::parse_step_def_manifest(n@fixture.name@::kStepDefinitions, manifest, errors))
    {
        std::cerr << "invalid step definitions:" << nZucchini::to_string(errors) << std::endl;
        return 1;
    }

    nZucchini::install_zucchini_provider(argc, argv, manifest);
    return nZucchini::ZucchiniMain(argc, argv);
}
END
