include_guard(GLOBAL)

# The code generated by tpp2cpp needs lib_tpp's runtime headers (ArgType/Policy/Writer).
set(TPP_APPLY_PROJECT_COMPILE_OPTIONS OFF CACHE BOOL "" FORCE)
set(TPP_CONFIGURE_TESTS OFF CACHE BOOL "" FORCE)
set(TPP_FETCH_NLOHMANN_JSON OFF CACHE BOOL "" FORCE)
set(TPP_NLOHMANN_JSON_TARGET nlohmann_json CACHE STRING "" FORCE)
set(TPP_FETCH_GTEST OFF CACHE BOOL "" FORCE)
set(TPP_GTEST_MAIN_TARGET gtest_main CACHE STRING "" FORCE)

zucchini_dependency(
    NAME tpp
    PACKAGE lib_tpp
    REPO https://github.com/AnarchoSystems/tpp
    TAG v0.14.0
    FIND_PACKAGE_ARGS)

# tpp and tpp2cpp are build tools: fetched once via get-tpp.sh and exposed as imported executables.
set(ZUCCHINI_TPP_VERSION "v0.14.0" CACHE STRING "Version of the tpp toolchain to use.")
set(ZUCCHINI_TPP_BIN_DIR "${CMAKE_BINARY_DIR}/tpp-bin" CACHE PATH "Where the tpp build tools are placed.")
option(ZUCCHINI_FETCH_TPP "Download the tpp build tools with get-tpp.sh." ON)

set(ZUCCHINI_TPP_EXECUTABLE "${ZUCCHINI_TPP_BIN_DIR}/tpp")
set(ZUCCHINI_TPP2CPP_EXECUTABLE "${ZUCCHINI_TPP_BIN_DIR}/tpp2cpp")

if(ZUCCHINI_FETCH_TPP)
    add_custom_command(
        OUTPUT "${ZUCCHINI_TPP_EXECUTABLE}" "${ZUCCHINI_TPP2CPP_EXECUTABLE}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${ZUCCHINI_TPP_BIN_DIR}"
        COMMAND bash "${CMAKE_SOURCE_DIR}/get-tpp.sh"
                -exact-version "${ZUCCHINI_TPP_VERSION}"
                -o "${ZUCCHINI_TPP_BIN_DIR}"
                tpp tpp2cpp
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        COMMENT "Fetching tpp toolchain ${ZUCCHINI_TPP_VERSION}"
        VERBATIM
    )
    add_custom_target(ZucchiniTppTools DEPENDS "${ZUCCHINI_TPP_EXECUTABLE}" "${ZUCCHINI_TPP2CPP_EXECUTABLE}")
else()
    find_program(ZUCCHINI_TPP_EXECUTABLE tpp REQUIRED)
    find_program(ZUCCHINI_TPP2CPP_EXECUTABLE tpp2cpp REQUIRED)
    add_custom_target(ZucchiniTppTools)
endif()

# Compiles a tpp project and attaches the generated sources to a target.
function(zucchini_add_tpp target)
    cmake_parse_arguments(TPP "" "SOURCE_DIR;NAME;NAMESPACE" "EXTRA_INCLUDES" ${ARGN})

    set(generated "${CMAKE_CURRENT_BINARY_DIR}/tpp-generated")
    set(ir "${generated}/${TPP_NAME}.ir.json")
    set(types "${generated}/${TPP_NAME}_types.h")
    set(functions "${generated}/${TPP_NAME}_functions.h")
    set(implementation "${generated}/${TPP_NAME}_implementation.cc")

    set(namespace_args)
    if(TPP_NAMESPACE)
        set(namespace_args -ns ${TPP_NAMESPACE})
    endif()

    set(include_args -i "${types}")
    foreach(extra IN LISTS TPP_EXTRA_INCLUDES)
        list(APPEND include_args -i "${extra}")
    endforeach()

    file(GLOB tpp_sources CONFIGURE_DEPENDS "${TPP_SOURCE_DIR}/*.tpp" "${TPP_SOURCE_DIR}/tpp-config.json")

    add_custom_command(
        OUTPUT "${ir}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${generated}"
        COMMAND "${CMAKE_COMMAND}" -E env "${ZUCCHINI_TPP_EXECUTABLE}" "${TPP_SOURCE_DIR}" > "${ir}"
        DEPENDS ZucchiniTppTools "${ZUCCHINI_TPP_EXECUTABLE}" ${tpp_sources}
        COMMENT "tpp: compiling ${TPP_NAME}"
        VERBATIM
    )

    add_custom_command(
        OUTPUT "${types}"
        COMMAND "${ZUCCHINI_TPP2CPP_EXECUTABLE}" types --input "${ir}" ${namespace_args} > "${types}"
        DEPENDS "${ir}" "${ZUCCHINI_TPP2CPP_EXECUTABLE}"
        COMMENT "tpp2cpp: ${TPP_NAME}_types.h"
        VERBATIM
    )

    add_custom_command(
        OUTPUT "${functions}"
        COMMAND "${ZUCCHINI_TPP2CPP_EXECUTABLE}" functions --input "${ir}" ${namespace_args} ${include_args}
                > "${functions}"
        DEPENDS "${ir}" "${types}" "${ZUCCHINI_TPP2CPP_EXECUTABLE}"
        COMMENT "tpp2cpp: ${TPP_NAME}_functions.h"
        VERBATIM
    )

    add_custom_command(
        OUTPUT "${implementation}"
        COMMAND "${ZUCCHINI_TPP2CPP_EXECUTABLE}" impl --input "${ir}" ${namespace_args} -i "${functions}"
                > "${implementation}"
        DEPENDS "${ir}" "${functions}" "${ZUCCHINI_TPP2CPP_EXECUTABLE}"
        COMMENT "tpp2cpp: ${TPP_NAME}_implementation.cc"
        VERBATIM
    )

    target_sources(${target} PRIVATE "${implementation}" "${functions}" "${types}")
    target_include_directories(${target} PRIVATE "${generated}")
endfunction()
